name: MacOS

on: [push, pull_request]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2

    - name: 配置 vcpkg
      uses: lukka/run-vcpkg@v7
      with:
        vcpkgDirectory: '${{github.workspace}}/vcpkg'
        vcpkgTriplet: arm64-osx
        # 2025.07.11
        vcpkgGitCommitId: 'efcfaaf60d7ec57a159fc3110403d939bfb69729'
        vcpkgArguments: 'openssl'

    - name: 安装指定 CMake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '3.30.5'

    - name: 编译
      uses: lukka/run-cmake@v3
      with:
        useVcpkgToolchainFile: true
        buildDirectory: '${{github.workspace}}/build'
        cmakeAppendedArgs: ''
        cmakeBuildType: 'RelWithDebInfo'
